<a href="https://colab.research.google.com/github/tKaiB/Capstone_Chicago/blob/main/Cap_Chicago_Crime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np

## Importing dataset

In [2]:
## Opening the CSV
url = 'https://raw.githubusercontent.com/tKaiB/Capstone_Chicago/refs/heads/main/datasets/Crime%202020_part1.csv'
url2 = 'https://raw.githubusercontent.com/tKaiB/Capstone_Chicago/refs/heads/main/datasets/Crime%202020_part2.csv'
url3 = 'https://raw.githubusercontent.com/tKaiB/Capstone_Chicago/refs/heads/main/datasets/Crime%202021_part1.csv'
url4 = 'https://raw.githubusercontent.com/tKaiB/Capstone_Chicago/refs/heads/main/datasets/Crime%202021_part2.csv'
url5 = 'https://raw.githubusercontent.com/tKaiB/Capstone_Chicago/refs/heads/main/datasets/Crime%202022_part1.csv'
url6 = 'https://raw.githubusercontent.com/tKaiB/Capstone_Chicago/refs/heads/main/datasets/Crime%202022_part2.csv'

# Read all the files and concat them by ignoring the
urls = [url
        ,url2
        ,url3
        ,url4
        ,url5
        ,url6
      ]
df_list = [pd.read_csv(url) for url in urls]
df = pd.concat(df_list, ignore_index=True)

### Uncleaned Dataset

In [3]:
df

,ID,Case Number,Date,Crime_Type_ID,Location_Type_ID,Arrest,Domestic,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Latitude,Longitude,Year,Updated On,Location
0,12016034,JD193556,01/01/2020 12:00:00 AM,1,1,False,False,1434,14,32.0,22.0,1160263.0,1912391.0,41.915306,-87.686639,2020,03/26/2020 03:45:12 PM,"(41.915306069, -87.686639247)"
1,12220321,JD430436,01/01/2020 12:00:00 AM,2,2,False,True,413,4,8.0,47.0,1184157.0,1844395.0,41.728192,-87.600985,2020,12/19/2020 03:45:59 PM,"(41.728192429, -87.600985433)"
2,12013828,JD191019,01/01/2020 12:00:00 AM,3,1,False,False,814,8,22.0,56.0,1143770.0,1874726.0,41.812274,-87.748177,2020,03/28/2020 03:47:02 PM,"(41.81227369, -87.748176594)"
3,12019692,JD197444,01/01/2020 12:00:00 AM,1,1,False,False,1922,19,47.0,6.0,1164983.0,1921507.0,41.940222,-87.669039,2020,04/01/2020 03:50:17 PM,"(41.940221932, -87.669039008)"
4,12843813,JF415893,01/01/2020 12:00:00 AM,1,1,False,False,331,3,5.0,43.0,NaN,NaN,NaN,NaN,2020,09/30/2022 04:48:19 PM,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639401,12915874,JF502169,12/07/2022 11:50:00 PM,64,124,False,False,813,8,23.0,65.0,1150629.0,1865174.0,41.785931,-87.723266,2022,12/14/2022 03:49:33 PM,"(41.785930664, -87.723266186)"
639402,12915875,JF502171,12/07/2022 11:51:00 PM,312,1,False,True,221,2,4.0,39.0,1182936.0,1875860.0,41.814564,-87.604481,2022,12/14/2022 03:49:33 PM,"(41.814563821, -87.604481355)"
639403,12917956,JF502185,12/07/2022 11:52:00 PM,11,11,False,True,1112,11,27.0,23.0,1151546.0,1905984.0,41.897901,-87.718833,2022,12/14/2022 03:49:33 PM,"(41.897900553, -87.718833412)"
639404,12915844,JF502180,12/07/2022 11:58:00 PM,221,11,True,False,734,7,6.0,67.0,1168578.0,1856355.0,41.761362,-87.657710,2022,12/14/2022 03:49:33 PM,"(41.761361892, -87.657710237)"
639405,12915894,JF502215,12/07/2022 11:59:00 PM,307,85,True,False,1011,10,24.0,29.0,1150244.0,1894089.0,41.865285,-87.723926,2022,12/14/2022 03:49:33 PM,"(41.865284862, -87.723925799)"

In [4]:
df.head()

,ID,Case Number,Date,Crime_Type_ID,Location_Type_ID,Arrest,Domestic,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Latitude,Longitude,Year,Updated On,Location
0,12016034,JD193556,01/01/2020 12:00:00 AM,1,1,False,False,1434,14,32.0,22.0,1160263.0,1912391.0,41.915306,-87.686639,2020,03/26/2020 03:45:12 PM,"(41.915306069, -87.686639247)"
1,12220321,JD430436,01/01/2020 12:00:00 AM,2,2,False,True,413,4,8.0,47.0,1184157.0,1844395.0,41.728192,-87.600985,2020,12/19/2020 03:45:59 PM,"(41.728192429, -87.600985433)"
2,12013828,JD191019,01/01/2020 12:00:00 AM,3,1,False,False,814,8,22.0,56.0,1143770.0,1874726.0,41.812274,-87.748177,2020,03/28/2020 03:47:02 PM,"(41.81227369, -87.748176594)"
3,12019692,JD197444,01/01/2020 12:00:00 AM,1,1,False,False,1922,19,47.0,6.0,1164983.0,1921507.0,41.940222,-87.669039,2020,04/01/2020 03:50:17 PM,"(41.940221932, -87.669039008)"
4,12843813,JF415893,01/01/2020 12:00:00 AM,1,1,False,False,331,3,5.0,43.0,NaN,NaN,NaN,NaN,2020,09/30/2022 04:48:19 PM,NaN

In [5]:
df.shape

(639406, 18)

In [6]:
## Remove those locations have null X/Y, Lat/Lon and Location
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 639406 entries, 0 to 639405
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                639406 non-null  int64
 1   Case Number       639406 non-null  object
 2   Date              639406 non-null  object
 3   Crime_Type_ID     639406 non-null  int64
 4   Location_Type_ID  639406 non-null  int64
 5   Arrest            639406 non-null  bool
 6   Domestic          639406 non-null  bool
 7   Beat              639406 non-null  int64
 8   District          639406 non-null  int64
 9   Ward              639376 non-null  float64
 10  Community Area    639405 non-null  float64
 11  X Coordinate      629371 non-null  float64
 12  Y Coordinate      629371 non-null  float64
 13  Latitude          629371 non-null  float64
 14  Longitude         629371 non-null  float64
 15  Year              639406 non-null  int64
 16  Updated On        639406 non-null  object
 17  Location          629371 non-null  object
dtypes: bool(2), float64(6), int64(6), object(4)
memory usage: 79.3+ MB

## Removing unnecessary columns

In [7]:
## "ID" and "Case Numbers" are not relevant to us as it doesn't give us additional insights to the crimes
df.drop(['ID', 'Case Number', 'Updated On'], axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 639406 entries, 0 to 639405
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              639406 non-null  object
 1   Crime_Type_ID     639406 non-null  int64
 2   Location_Type_ID  639406 non-null  int64
 3   Arrest            639406 non-null  bool
 4   Domestic          639406 non-null  bool
 5   Beat              639406 non-null  int64
 6   District          639406 non-null  int64
 7   Ward              639376 non-null  float64
 8   Community Area    639405 non-null  float64
 9   X Coordinate      629371 non-null  float64
 10  Y Coordinate      629371 non-null  float64
 11  Latitude          629371 non-null  float64
 12  Longitude         629371 non-null  float64
 13  Year              639406 non-null  int64
 14  Location          629371 non-null  object
dtypes: bool(2), float64(6), int64(5), object(2)
memory usage: 64.6+ MB

In [8]:
## Removing X/Y Coordinate and Location
df.drop(['X Coordinate', 'Y Coordinate', 'Location'], axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 639406 entries, 0 to 639405
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              639406 non-null  object
 1   Crime_Type_ID     639406 non-null  int64
 2   Location_Type_ID  639406 non-null  int64
 3   Arrest            639406 non-null  bool
 4   Domestic          639406 non-null  bool
 5   Beat              639406 non-null  int64
 6   District          639406 non-null  int64
 7   Ward              639376 non-null  float64
 8   Community Area    639405 non-null  float64
 9   Latitude          629371 non-null  float64
 10  Longitude         629371 non-null  float64
 11  Year              639406 non-null  int64
dtypes: bool(2), float64(4), int64(5), object(1)
memory usage: 50.0+ MB

## Cleansing the dataset for any missing values

In [9]:
df.dropna(subset=['Latitude', 'Longitude'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 629371 entries, 0 to 639405
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              629371 non-null  object
 1   Crime_Type_ID     629371 non-null  int64
 2   Location_Type_ID  629371 non-null  int64
 3   Arrest            629371 non-null  bool
 4   Domestic          629371 non-null  bool
 5   Beat              629371 non-null  int64
 6   District          629371 non-null  int64
 7   Ward              629342 non-null  float64
 8   Community Area    629370 non-null  float64
 9   Latitude          629371 non-null  float64
 10  Longitude         629371 non-null  float64
 11  Year              629371 non-null  int64
dtypes: bool(2), float64(4), int64(5), object(1)
memory usage: 54.0+ MB

In [10]:
# Since it is only 29 missing entries without any values in "Ward" and 1 missing in "Community Area"
# We will just remove those entries to not have any outliers that affects the model
df.dropna(subset=['Ward', 'Community Area'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 629342 entries, 0 to 639405
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              629342 non-null  object
 1   Crime_Type_ID     629342 non-null  int64
 2   Location_Type_ID  629342 non-null  int64
 3   Arrest            629342 non-null  bool
 4   Domestic          629342 non-null  bool
 5   Beat              629342 non-null  int64
 6   District          629342 non-null  int64
 7   Ward              629342 non-null  float64
 8   Community Area    629342 non-null  float64
 9   Latitude          629342 non-null  float64
 10  Longitude         629342 non-null  float64
 11  Year              629342 non-null  int64
dtypes: bool(2), float64(4), int64(5), object(1)
memory usage: 54.0+ MB

In [11]:
# Change the type of "Ward" and "Community Area" to int64
df['Ward'] = df['Ward'].astype('int64')
df['Community Area'] = df['Community Area'].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 629342 entries, 0 to 639405
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              629342 non-null  object
 1   Crime_Type_ID     629342 non-null  int64
 2   Location_Type_ID  629342 non-null  int64
 3   Arrest            629342 non-null  bool
 4   Domestic          629342 non-null  bool
 5   Beat              629342 non-null  int64
 6   District          629342 non-null  int64
 7   Ward              629342 non-null  int64
 8   Community Area    629342 non-null  int64
 9   Latitude          629342 non-null  float64
 10  Longitude         629342 non-null  float64
 11  Year              629342 non-null  int64
dtypes: bool(2), float64(2), int64(7), object(1)
memory usage: 54.0+ MB

In [12]:
# Remove all rows where Location_Type_ID is 7
df = df[df['Location_Type_ID'] != 7]

# Reset index since rows were removed
df.reset_index(drop=True, inplace=True)

# Verify the remaining shape and inspect data
print("New shape of DataFrame:", df.shape)

New shape of DataFrame: (627163, 12)

In [13]:
df

,Date,Crime_Type_ID,Location_Type_ID,Arrest,Domestic,Beat,District,Ward,Community Area,Latitude,Longitude,Year
0,01/01/2020 12:00:00 AM,1,1,False,False,1434,14,32,22,41.915306,-87.686639,2020
1,01/01/2020 12:00:00 AM,2,2,False,True,413,4,8,47,41.728192,-87.600985,2020
2,01/01/2020 12:00:00 AM,3,1,False,False,814,8,22,56,41.812274,-87.748177,2020
3,01/01/2020 12:00:00 AM,1,1,False,False,1922,19,47,6,41.940222,-87.669039,2020
4,01/01/2020 12:00:00 AM,4,2,False,False,831,8,18,66,41.762067,-87.699077,2020
...,...,...,...,...,...,...,...,...,...,...,...,...
627158,12/07/2022 11:50:00 PM,64,124,False,False,813,8,23,65,41.785931,-87.723266,2022
627159,12/07/2022 11:51:00 PM,312,1,False,True,221,2,4,39,41.814564,-87.604481,2022
627160,12/07/2022 11:52:00 PM,11,11,False,True,1112,11,27,23,41.897901,-87.718833,2022
627161,12/07/2022 11:58:00 PM,221,11,True,False,734,7,6,67,41.761362,-87.657710,2022
627162,12/07/2022 11:59:00 PM,307,85,True,False,1011,10,24,29,41.865285,-87.723926,2022

## Adding columns based on the current information acquired

In [ ]:
# Convert Date column to datetime format explicitly
df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y %I:%M:%S %p')

# Extract hour and bin into 4 categories:
# 1 (00:00 ~ 05:59), 2 (6:00 ~ 11:59), 3 (12:00 ~ 17:59), 4 (18:00 ~ 23:59)
df['Time_Of_Day'] = pd.cut(
    df['Date'].dt.hour,
    bins=[-1, 5, 11, 17, 24],
    labels=[1, 2, 3, 4]
).astype(int)

In [15]:
df

,Date,Crime_Type_ID,Location_Type_ID,Arrest,Domestic,Beat,District,Ward,Community Area,Latitude,Longitude,Year,Time_Of_Day
0,2020-01-01 00:00:00,1,1,False,False,1434,14,32,22,41.915306,-87.686639,2020,1
1,2020-01-01 00:00:00,2,2,False,True,413,4,8,47,41.728192,-87.600985,2020,1
2,2020-01-01 00:00:00,3,1,False,False,814,8,22,56,41.812274,-87.748177,2020,1
3,2020-01-01 00:00:00,1,1,False,False,1922,19,47,6,41.940222,-87.669039,2020,1
4,2020-01-01 00:00:00,4,2,False,False,831,8,18,66,41.762067,-87.699077,2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
627158,2022-12-07 23:50:00,64,124,False,False,813,8,23,65,41.785931,-87.723266,2022,4
627159,2022-12-07 23:51:00,312,1,False,True,221,2,4,39,41.814564,-87.604481,2022,4
627160,2022-12-07 23:52:00,11,11,False,True,1112,11,27,23,41.897901,-87.718833,2022,4
627161,2022-12-07 23:58:00,221,11,True,False,734,7,6,67,41.761362,-87.657710,2022,4
627162,2022-12-07 23:59:00,307,85,True,False,1011,10,24,29,41.865285,-87.723926,2022,4

In [16]:
# Extract the day name (e.g., Monday, Tuesday, etc.)
df['Day_of_Week'] = df['Date'].dt.day_name()

/tmp/ipykernel_24930/360236289.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Day_of_Week'] = df['Date'].dt.day_name()

In [17]:
df

,Date,Crime_Type_ID,Location_Type_ID,Arrest,Domestic,Beat,District,Ward,Community Area,Latitude,Longitude,Year,Time_Of_Day,Day_of_Week
0,2020-01-01 00:00:00,1,1,False,False,1434,14,32,22,41.915306,-87.686639,2020,1,Wednesday
1,2020-01-01 00:00:00,2,2,False,True,413,4,8,47,41.728192,-87.600985,2020,1,Wednesday
2,2020-01-01 00:00:00,3,1,False,False,814,8,22,56,41.812274,-87.748177,2020,1,Wednesday
3,2020-01-01 00:00:00,1,1,False,False,1922,19,47,6,41.940222,-87.669039,2020,1,Wednesday
4,2020-01-01 00:00:00,4,2,False,False,831,8,18,66,41.762067,-87.699077,2020,1,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627158,2022-12-07 23:50:00,64,124,False,False,813,8,23,65,41.785931,-87.723266,2022,4,Wednesday
627159,2022-12-07 23:51:00,312,1,False,True,221,2,4,39,41.814564,-87.604481,2022,4,Wednesday
627160,2022-12-07 23:52:00,11,11,False,True,1112,11,27,23,41.897901,-87.718833,2022,4,Wednesday
627161,2022-12-07 23:58:00,221,11,True,False,734,7,6,67,41.761362,-87.657710,2022,4,Wednesday
627162,2022-12-07 23:59:00,307,85,True,False,1011,10,24,29,41.865285,-87.723926,2022,4,Wednesday

### --- Holiday Legend Mapping ---
- ID: 0 -> Non-Holiday
- ID: 1 -> New Year's Day
- ID: 2 -> Martin Luther King Jr. Day
- ID: 3 -> Lincoln's Birthday
- ID: 4 -> Washington's Birthday
- ID: 5 -> Casimir Pulaski Day
- ID: 6 -> Memorial Day
- ID: 7 -> Independence Day (observed)
- ID: 8 -> Independence Day

In [18]:
import holidays

# Initialize Illinois/US holidays
us_holidays = holidays.US(state='IL')

# Extract unique dates in YYYY-MM-DD format to speed up holiday lookup
unique_dates = df['Date'].dt.date.unique()

# Create a mapping dictionary for holidays found in our dataset
holiday_mapping = {}
current_label = 1

# Assign 0 for non-holidays
holiday_mapping['Non-Holiday'] = 0

# Check each unique date and build our mapping
date_to_holiday_name = {}
for d in unique_dates:
    h_name = us_holidays.get(d)
    if h_name:
        # Clean holiday names slightly (e.g., handling Observed days if needed)
        if h_name not in holiday_mapping:
            holiday_mapping[h_name] = current_label
            current_label += 1
        date_to_holiday_name[d] = h_name
    else:
        date_to_holiday_name[d] = 'Non-Holiday'

# Create the 'Holiday' column by mapping the date to its holiday name and then to its number
df['Holiday_Name'] = df['Date'].dt.date.map(date_to_holiday_name)
df['Holiday'] = df['Holiday_Name'].map(holiday_mapping)

# Drop the temporary Holiday_Name helper column if you prefer to keep the dataset clean
df.drop(columns=['Holiday_Name'], inplace=True)

# Print the legend mapping numbers to holiday names
print("--- Holiday Legend Mapping ---")
for name, label in sorted(holiday_mapping.items(), key=lambda x: x[1]):
    print(f"ID: {label} -> {name}")

# Verify by showing some detected holidays
display(df[df['Holiday'] > 0][['Date', 'Holiday']].head())

--- Holiday Legend Mapping ---
ID: 0 -> Non-Holiday
ID: 1 -> New Year's Day
ID: 2 -> Martin Luther King Jr. Day
ID: 3 -> Lincoln's Birthday
ID: 4 -> Washington's Birthday
ID: 5 -> Casimir Pulaski Day
ID: 6 -> Memorial Day
ID: 7 -> Independence Day (observed)
ID: 8 -> Independence Day
ID: 9 -> Labor Day
ID: 10 -> Columbus Day
ID: 11 -> Election Day
ID: 12 -> Veterans Day
ID: 13 -> Thanksgiving Day
ID: 14 -> Christmas Day
ID: 15 -> Juneteenth National Independence Day (observed)
ID: 16 -> Juneteenth National Independence Day
ID: 17 -> Christmas Day (observed)
ID: 18 -> New Year's Day (observed)
ID: 19 -> Lincoln's Birthday (observed)

/tmp/ipykernel_24930/1170851072.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Holiday_Name'] = df['Date'].dt.date.map(date_to_holiday_name)
/tmp/ipykernel_24930/1170851072.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Holiday'] = df['Holiday_Name'].map(holiday_mapping)
/tmp/ipykernel_24930/1170851072.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['Holiday_Name'], inplace=True)

        Date  Holiday
0 2020-01-01        1
1 2020-01-01        1
2 2020-01-01        1
3 2020-01-01        1
4 2020-01-01        1

### Merging

#### Location Types

In [19]:
import pandas as pd

# For Location Types
location_types_url = 'https://raw.githubusercontent.com/tKaiB/Capstone_Chicago/refs/heads/main/Location%20Types.csv'
## Location Types
location_types_df = pd.read_csv(location_types_url, skiprows=3, header=None)

# Transpose so each row becomes a record
location_types_df = location_types_df.T

# # Drop the first row (was the original row index 0, i.e., the "Locations:" header cell)
location_types_df = location_types_df.iloc[1:].reset_index(drop=True)

# # Rename columns for easy combining after
location_types_df.columns = ['Location_Type_ID', 'Location Description']


# Convert ID column to int to match your main df
location_types_df['Location_Type_ID'] = pd.to_numeric(location_types_df['Location_Type_ID'], errors='coerce').dropna().astype(int)

# Let's inspect their columns to make sure we map them correctly
print("Location Types Columns:", location_types_df.columns.tolist())

location_types_df

Location Types Columns: ['Location_Type_ID', 'Location Description']

     Location_Type_ID   Location Description
0                   1              APARTMENT
1                   2              RESIDENCE
2                   3        OTHER (SPECIFY)
3                   4          BAR OR TAVERN
4                   5        VACANT LOT/LAND
..                ...                    ...
172               173              CHA LOBBY
173               174        POLICE FACILITY
174               175             RIVER BANK
175               176                 TAVERN
176               177  PUBLIC GRAMMAR SCHOOL

[177 rows x 2 columns]

#### Crime Types

In [20]:
# Define the URLs for the lookup reference tables
crime_types_url = 'https://raw.githubusercontent.com/tKaiB/Capstone_Chicago/refs/heads/main/Crime%20Types.csv'

# Load the reference datasets
crime_types_df = pd.read_csv(crime_types_url, usecols=[0,1])

# The 3rd and 4th column were not useful to us as it would add more noise to the modelling later on

# Let's inspect their columns to make sure we map them correctly
print("Crime Types Columns:", crime_types_df.columns.tolist())
crime_types_df
# We use 'left' join to ensure we keep all our main crime records even if a description is missing
# df = df.merge(crime_types_df, on='Crime_Type_ID', how='left')

Crime Types Columns: ['Crime_Type_ID', 'Primary Type']

     Crime_Type_ID                Primary Type
0                1          DECEPTIVE PRACTICE
1                2  OFFENSE INVOLVING CHILDREN
2                3     CRIMINAL SEXUAL ASSAULT
3                4          DECEPTIVE PRACTICE
4                5                       THEFT
..             ...                         ...
468            469                PROSTITUTION
469            470                   NARCOTICS
470            471         MOTOR VEHICLE THEFT
471            472                    HOMICIDE
472            473                   NARCOTICS

[473 rows x 2 columns]

In [21]:
# Merge with our main DataFrame
# We use 'left' join to ensure we keep all our main crime records even if a description is missing
df = df.merge(crime_types_df, on='Crime_Type_ID', how='left')
df = df.merge(location_types_df, on='Location_Type_ID', how='left')
df

,Date,Crime_Type_ID,Location_Type_ID,Arrest,Domestic,Beat,District,Ward,Community Area,Latitude,Longitude,Year,Time_Of_Day,Day_of_Week,Holiday,Primary Type,Location Description
0,2020-01-01 00:00:00,1,1,False,False,1434,14,32,22,41.915306,-87.686639,2020,1,Wednesday,1,DECEPTIVE PRACTICE,APARTMENT
1,2020-01-01 00:00:00,2,2,False,True,413,4,8,47,41.728192,-87.600985,2020,1,Wednesday,1,OFFENSE INVOLVING CHILDREN,RESIDENCE
2,2020-01-01 00:00:00,3,1,False,False,814,8,22,56,41.812274,-87.748177,2020,1,Wednesday,1,CRIMINAL SEXUAL ASSAULT,APARTMENT
3,2020-01-01 00:00:00,1,1,False,False,1922,19,47,6,41.940222,-87.669039,2020,1,Wednesday,1,DECEPTIVE PRACTICE,APARTMENT
4,2020-01-01 00:00:00,4,2,False,False,831,8,18,66,41.762067,-87.699077,2020,1,Wednesday,1,DECEPTIVE PRACTICE,RESIDENCE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627158,2022-12-07 23:50:00,64,124,False,False,813,8,23,65,41.785931,-87.723266,2022,4,Wednesday,0,THEFT,TAVERN / LIQUOR STORE
627159,2022-12-07 23:51:00,312,1,False,True,221,2,4,39,41.814564,-87.604481,2022,4,Wednesday,0,BATTERY,APARTMENT
627160,2022-12-07 23:52:00,11,11,False,True,1112,11,27,23,41.897901,-87.718833,2022,4,Wednesday,0,BATTERY,STREET
627161,2022-12-07 23:58:00,221,11,True,False,734,7,6,67,41.761362,-87.657710,2022,4,Wednesday,0,NARCOTICS,STREET
627162,2022-12-07 23:59:00,307,85,True,False,1011,10,24,29,41.865285,-87.723926,2022,4,Wednesday,0,OTHER OFFENSE,ABANDONED BUILDING